[phases.setup]
nixPkgs = ["nodejs_22", "gcc", "gnumake", "python3"]

[phases.install]
dependsOn = ["setup"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
cmd = "node server/index.js"
